/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.AlumnoData;
import Persistencia.Conexion;
import Persistencia.InscripcionData;
import Persistencia.MateriaData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class vistaCargaNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaCargaNotas
     */
    
    private ArrayList<Materia> listaM;
    private ArrayList<Alumno> listaA;
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoData aData;
    private Inscripcion inscripcionFicticia;

    private DefaultTableModel modeloTabla;
    
    Conexion con = new Conexion();
    
    
    public vistaCargaNotas() {
        initComponents();
        
        aData = new AlumnoData(con);
        listaA = (ArrayList<Alumno>)aData.listarAlumnos();
        modeloTabla = new DefaultTableModel();
        inscData = new InscripcionData(con);
        mData = new MateriaData(con);
        cargarAlumnos();
        cargarColumnasTabla();
        materiasInscriptas();
       
              
        
    }
    

    private void cargarAlumnos(){
        
        for(Alumno alumno: listaA){
            
            jcb_alumnosNotas.addItem(alumno);
        
        }
        
        
    }
    
    private void cargarColumnasTabla(){
        
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Nota");
        for(Object it: filaCabecera){
            modeloTabla.addColumn(it);
        }
        tbl_alumnosNotas.setModel(modeloTabla);
        
    }
    
    private void borrarFilaTabla(){
        
        int indice = modeloTabla.getRowCount() -1;
        
        
        for(int i = indice;i >= 0; i--){
            modeloTabla.removeRow(i);
        }
        
        
    }
    
    private void materiasInscriptas(){
        
        borrarFilaTabla();
        Alumno seleccion = (Alumno)jcb_alumnosNotas.getSelectedItem();
        listaM = (ArrayList) inscData.obtenerMateriasCursadas(seleccion.getId_alumno());
        
        
        for(Materia m: listaM){
            
            
            
            modeloTabla.addRow(new Object[] {
                m.getId_materia(), 
                m.getNombre(),
                inscData.buscarNotaInscripcion(seleccion.getId_alumno(), m.getId_materia())
                
                
 
            });
        }
        
        
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulonotas = new javax.swing.JLabel();
        lbl_alumnoNotas = new javax.swing.JLabel();
        jcb_alumnosNotas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_alumnosNotas = new javax.swing.JTable();
        btn_guardarNotas = new javax.swing.JButton();
        btn_cancelarNotas = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_titulonotas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titulonotas.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulonotas.setText("CARGA DE NOTAS");

        lbl_alumnoNotas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_alumnoNotas.setForeground(new java.awt.Color(0, 0, 0));
        lbl_alumnoNotas.setText("Alumno:");

        jcb_alumnosNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnosNotasActionPerformed(evt);
            }
        });

        tbl_alumnosNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_alumnosNotas);

        btn_guardarNotas.setText("Guardar");
        btn_guardarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarNotasActionPerformed(evt);
            }
        });

        btn_cancelarNotas.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardarNotas)
                .addGap(51, 51, 51)
                .addComponent(btn_cancelarNotas)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_alumnoNotas)
                                .addGap(66, 66, 66)
                                .addComponent(jcb_alumnosNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lbl_titulonotas)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_titulonotas)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_alumnoNotas)
                    .addComponent(jcb_alumnosNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarNotas)
                    .addComponent(btn_cancelarNotas))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_alumnosNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnosNotasActionPerformed
        materiasInscriptas();
    }//GEN-LAST:event_jcb_alumnosNotasActionPerformed

    private void btn_guardarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarNotasActionPerformed
        
        Alumno seleccion =(Alumno) jcb_alumnosNotas.getSelectedItem();
        InscripcionData idata = new InscripcionData(con);
        
        
        
        int filaSeleccionada = tbl_alumnosNotas.getSelectedRow();
        
        if(filaSeleccionada != -1){
            
            
            Object idMateriaObjeto =(Integer) modeloTabla.getValueAt(filaSeleccionada, 0);
            int idMateria = Integer.parseInt(String.valueOf(idMateriaObjeto));
            
            Materia mModificada = mData.buscarMateria(idMateria);
            
            Object notaMateriaObjeto = modeloTabla.getValueAt(filaSeleccionada, 2);
            int notaMateria = Integer.parseInt(String.valueOf(notaMateriaObjeto));
            
            
            Inscripcion i = new Inscripcion(seleccion, mModificada, notaMateria);
            
            idata.actualizarInscripcion(i);
        
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_guardarNotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarNotas;
    private javax.swing.JButton btn_guardarNotas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Alumno> jcb_alumnosNotas;
    private javax.swing.JLabel lbl_alumnoNotas;
    private javax.swing.JLabel lbl_titulonotas;
    private javax.swing.JTable tbl_alumnosNotas;
    // End of variables declaration//GEN-END:variables
}
