/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Rickert
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dktp_escritorio = new javax.swing.JDesktopPane();
        menu_principal = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_materias = new javax.swing.JMenu();
        menu_alumnos = new javax.swing.JMenu();
        menu_inscripciones = new javax.swing.JMenu();
        menu_carga = new javax.swing.JMenu();
        menu_consultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dktp_escritorioLayout = new javax.swing.GroupLayout(dktp_escritorio);
        dktp_escritorio.setLayout(dktp_escritorioLayout);
        dktp_escritorioLayout.setHorizontalGroup(
            dktp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        dktp_escritorioLayout.setVerticalGroup(
            dktp_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        menu_archivo.setText("Archivo");
        menu_principal.add(menu_archivo);

        menu_materias.setText("Materias");
        menu_principal.add(menu_materias);

        menu_alumnos.setText("Alumnos");
        menu_principal.add(menu_alumnos);

        menu_inscripciones.setText("Inscripciones");
        menu_principal.add(menu_inscripciones);

        menu_carga.setText("Carga de Notas");
        menu_principal.add(menu_carga);

        menu_consultas.setText("Consultas");
        menu_principal.add(menu_consultas);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktp_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dktp_escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dktp_escritorio;
    private javax.swing.JMenu menu_alumnos;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_carga;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_inscripciones;
    private javax.swing.JMenu menu_materias;
    private javax.swing.JMenuBar menu_principal;
    // End of variables declaration//GEN-END:variables
}
