/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.AlumnoData;
import Persistencia.Conexion;
import Persistencia.InscripcionData;
import Persistencia.MateriaData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class vistaListarInscripciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaListarInscripciones
     */
    
    private ArrayList<Materia> listaM;
    private ArrayList<Alumno> listaA;
    private InscripcionData inscData;
    private MateriaData mData;
    private AlumnoData aData;
    private Inscripcion inscripcionFicticia;

    private DefaultTableModel modeloTabla;
    
    Conexion con = new Conexion();
    
    
    public vistaListarInscripciones() {
        initComponents();
        
        aData = new AlumnoData(con);
        mData = new MateriaData(con);
        inscData = new InscripcionData(con);
        listaA = (ArrayList<Alumno>)aData.listarAlumnos();
        listaM = (ArrayList<Materia>)mData.listarMaterias();
        modeloTabla = new DefaultTableModel();
        
        
        cargarMaterias();
        cargarColumnasTabla();
        alumnosInscriptos();
        
    }

    
    
    
    
    private void cargarMaterias(){
        
        for(Materia materia: listaM){
            
            jcb_materiaListado.addItem(materia);
        
        }
        
        
    }
    
    
    private void cargarColumnasTabla(){
        
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Apellido");
        for(Object it: filaCabecera){
            modeloTabla.addColumn(it);
        }
        tbl_materiaListados.setModel(modeloTabla);
        
    }
    
    
    private void borrarFilaTabla(){
        
        int indice = modeloTabla.getRowCount() -1;
        
        
        for(int i = indice;i >= 0; i--){
            modeloTabla.removeRow(i);
        }
        
        
    }
    
    
    private void alumnosInscriptos(){
        
        borrarFilaTabla();
        Materia seleccion = (Materia)jcb_materiaListado.getSelectedItem();
        listaA = (ArrayList) inscData.obtenerAlumnosInscriptos(seleccion.getId_materia());
        
        
        for(Alumno a: listaA){
            
            
            
            modeloTabla.addRow(new Object[] {
                a.getId_alumno(), 
                a.getNombre(),
                a.getApellido()
                
                
                
 
            });
        }
        
        
        
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloListado = new javax.swing.JLabel();
        lbl_materiaListado = new javax.swing.JLabel();
        jcb_materiaListado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_materiaListados = new javax.swing.JTable();
        btn_salirListado = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloListado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tituloListado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloListado.setText("LISTADO DE INSCRIPCIONES ");

        lbl_materiaListado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_materiaListado.setForeground(new java.awt.Color(0, 0, 0));
        lbl_materiaListado.setText("MATERIA:");

        jcb_materiaListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_materiaListadoActionPerformed(evt);
            }
        });

        tbl_materiaListados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_materiaListados);

        btn_salirListado.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lbl_materiaListado)
                        .addGap(41, 41, 41)
                        .addComponent(jcb_materiaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_salirListado)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tituloListado)
                        .addGap(157, 157, 157))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_tituloListado)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_materiaListado)
                    .addComponent(jcb_materiaListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salirListado)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_materiaListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_materiaListadoActionPerformed
        alumnosInscriptos();
    }//GEN-LAST:event_jcb_materiaListadoActionPerformed


    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salirListado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Materia> jcb_materiaListado;
    private javax.swing.JLabel lbl_materiaListado;
    private javax.swing.JLabel lbl_tituloListado;
    private javax.swing.JTable tbl_materiaListados;
    // End of variables declaration//GEN-END:variables
}
