/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Persistencia.AlumnoData;
import Persistencia.Conexion;
import Persistencia.InscripcionData;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class vistaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInscripcion
     */
    public vistaInscripcion() {
        initComponents();
        cargarAlumnos();
        cargarCategoriasInscripcion();
    }

    
    private DefaultTableModel tablaInscripciones = new DefaultTableModel(){
        
        public boolean iscellEditable(int f, int c){
         
            return false;
            
        }
        
        
    };
    
    
    
    Conexion con = new Conexion();
    AlumnoData operacionesAlumnos = new AlumnoData(con);
    InscripcionData operacionesInscripciones = new InscripcionData(con);
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloInscripcion = new javax.swing.JLabel();
        lbl_alumnoInscripcion = new javax.swing.JLabel();
        jcb_alumnosInscripcion = new javax.swing.JComboBox<>();
        lbl_listadoMaterias = new javax.swing.JLabel();
        jrb_inscripto = new javax.swing.JRadioButton();
        jrb_noinscripto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaInscripciones = new javax.swing.JTable();
        btn_inscribir = new javax.swing.JButton();
        btn_anularInscripcion = new javax.swing.JButton();
        btn_salirInscripcion = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloInscripcion.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 18)); // NOI18N
        lbl_tituloInscripcion.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloInscripcion.setText("FORMULARIO DE INSCRIPCION");

        lbl_alumnoInscripcion.setForeground(new java.awt.Color(0, 0, 0));
        lbl_alumnoInscripcion.setText("Alumno:");

        jcb_alumnosInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnosInscripcionActionPerformed(evt);
            }
        });

        lbl_listadoMaterias.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 14)); // NOI18N
        lbl_listadoMaterias.setForeground(new java.awt.Color(0, 0, 0));
        lbl_listadoMaterias.setText("Listado De Materias");

        jrb_inscripto.setForeground(new java.awt.Color(0, 0, 0));
        jrb_inscripto.setText("Inscripto");

        jrb_noinscripto.setForeground(new java.awt.Color(0, 0, 0));
        jrb_noinscripto.setText("No Inscripto");

        tbl_tablaInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaInscripciones);

        btn_inscribir.setText("Inscribir");

        btn_anularInscripcion.setText("Anular Inscripcion");

        btn_salirInscripcion.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_inscribir)
                        .addGap(60, 60, 60)
                        .addComponent(btn_anularInscripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salirInscripcion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbl_alumnoInscripcion)
                        .addGap(58, 58, 58)
                        .addComponent(jcb_alumnosInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lbl_listadoMaterias))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbl_tituloInscripcion)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jrb_inscripto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrb_noinscripto)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_tituloInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_alumnoInscripcion)
                    .addComponent(jcb_alumnosInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lbl_listadoMaterias)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_inscripto)
                    .addComponent(jrb_noinscripto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inscribir)
                    .addComponent(btn_anularInscripcion)
                    .addComponent(btn_salirInscripcion))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_alumnosInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnosInscripcionActionPerformed
        
        tablaInscripciones.setRowCount(0);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jcb_alumnosInscripcionActionPerformed

    
    
    public void cargarCategoriasInscripcion(){
        
        tablaInscripciones.addColumn("ID");
        tablaInscripciones.addColumn("Nombre");
        
        
        tbl_tablaInscripciones.setModel(tablaInscripciones);
        
        
        
    }
    
    
    
    
    public void cargarAlumnos(){
        
        
        
        jcb_alumnosInscripcion.removeAllItems();
        
        for(Alumno alumno: operacionesAlumnos.listarAlumnos()){
            
            jcb_alumnosInscripcion.addItem(alumno.getNombre() + " " + alumno.getApellido());
            
            
            
        }
        
        
        
        
        
        
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anularInscripcion;
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JButton btn_salirInscripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_alumnosInscripcion;
    private javax.swing.JRadioButton jrb_inscripto;
    private javax.swing.JRadioButton jrb_noinscripto;
    private javax.swing.JLabel lbl_alumnoInscripcion;
    private javax.swing.JLabel lbl_listadoMaterias;
    private javax.swing.JLabel lbl_tituloInscripcion;
    private javax.swing.JTable tbl_tablaInscripciones;
    // End of variables declaration//GEN-END:variables
}
